"""move_to_mapped_refactoring

Revision ID: 21681ec913e9
Revises: cd597f1ee2aa
Create Date: 2026-06-16 08:58:37.333190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21681ec913e9'
down_revision: Union[str, Sequence[str], None] = 'cd597f1ee2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
