"""add

Revision ID: 219263e66f1b
Revises: fc2c08c4e2e4
Create Date: 2026-06-13 05:58:43.415924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219263e66f1b'
down_revision: Union[str, Sequence[str], None] = 'fc2c08c4e2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'object', 'transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'object', type_='foreignkey')
    op.drop_column('object', 'transaction_id')
    # ### end Alembic commands ###
