"""move to mapped

Revision ID: cd597f1ee2aa
Revises: 219263e66f1b
Create Date: 2026-06-16 08:56:23.196515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd597f1ee2aa'
down_revision: Union[str, Sequence[str], None] = '219263e66f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('object', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('object', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('object', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('object', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('object', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('object', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
