upstream frontend-service {
    server service.frontend:5173;
}

upstream backend-service-fastapi {
    server service.fastapi:8000;
}

upstream smtp4dev-service {
    server service.smtp4dev;
}

upstream adminer-service {
    server service.adminer:8080;
}


# include /etc/nginx/mime.types;

server {
    listen 80;
    client_max_body_size 100M;

    location / {
        proxy_pass http://frontend-service;
        proxy_set_header X-Forwarded-Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;
    }

    location /adminer/ {
        proxy_pass http://adminer-service/;
        proxy_set_header X-Forwarded-Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;
    }

    location /smtp4dev/ {
        proxy_pass http://smtp4dev-service;
        proxy_set_header X-Forwarded-Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;

        # Для WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";        
    }

    # Настройки для backend/fastapi
    location /fastapi/ {
        proxy_pass http://backend-service-fastapi/;
        proxy_set_header X-Forwarded-Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;

        # Для WebSocket.
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    
    # Насстроки для вспомогательных сервисов для backend/fastapi
    # Два типа документации
    # Доступ осуществляется через аутентификацию
    location ~ ^/fastapi/(docs|redoc|openapi\.json)$ {
        proxy_pass http://backend-service-fastapi/$1;
        proxy_set_header X-Forwarded-Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;
    }

    # Для работы devtools на frontend и доступа к icons
    location ~ ^/(_nuxt|api/_nuxt_icon) {
        proxy_pass http://frontend-service;
        proxy_set_header X-Forwarded-Host $http_host; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Referer $http_referer;
        # 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    } 

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location /internal/sphinx/ {
        internal;
        alias /usr/share/nginx/html/static/sphinx_docs/;

        try_files $uri $uri/ =404;
    }


}